sudo: required
os: osx
osx_image: xcode7.3
#language: scala
scala:
  - "2.11.8"
cache:
  directories:
    - $HOME/.ivy2/cache
env:
  global:
    - MAVEN_REALM="Sonatype Nexus Repository Manager"
    - MAVEN_DOMAIN="oss.sonatype.org"
    - secure: "jWozY/nq5uaR23Pwz8mCELIc2phk0FePhRwLreG3VwtM39YUFzgzH3y9w2O8nButQGJi6s6fkZ8ubTGzC5bTf2+rJHliHGHoNOBYxAdzVdiSFXPLvQaJQ9G9ECvImxbXRskMcv9K9ppMANhoupjm3f20sg23f9Hcd93lGd+zig6mq2pABGw7UiMIvbtw7vJapg+Z2OM3EJMRFtWBmYjNnbuskVjycKFC8bJYbqq2A/OgSPMyVg9QBH66cCOX8joIApc/p/DO9k7uuEsQxts6TX9oDrNihKV0ur8+df7E8K1mYFNNFbOK8lgdDvwvNy4ejawrEMND4EdRAhL8VPRPYaWEfydju7Uf/fapVL4oPjCdwVFc8FWUdW6wRwDkmMDy8qJ29JwA8S1fU+uhDMuyfxvx8kD5xcPXh3Nv/QwDciUwKm66Bcn4dTZ52oZ4s7zJ2xG63oRVCeNCzhbJTuDzRcTmIPisb0i6ci67vQDumKKp0xE7brreM58+PI/WwV+wdhPkLXCcd0mEABkISDzS22MMBsl3OgLPWWOTdLvB79nz7V1fUa00t99HlwbIf8d/q5h4clTGBCo7lRgPU+P6EfyM0RS2i5pmW1Feh/xxv3DL88jPRq2IXi6yTAHbngt2F7CdBkdLSEVp060XxpZrd/zQhJ7AVW7QShONN59DI+k="
    - secure: "Y+XCid6ReIunKJvG6XR9W6/1P/VSIoQboThjn5Y6OM1y6QoPGnBQ9vFBkWyLGAKrUm7aHfWqCwla1MEUpV01g4fzCIIUjqGqEhoTdl7CwtGCqbkmr+KX9KQlzlyCaiTiZ+wdgpLqEMK+OC0riYK30oR5vNqQbmu9Q9ATeytLUYc99YUZc8QEUT8jTBmtY6wcUcsBJ4AWmUEo1dgsvoFjTSJHNDnvn+Xrhan2v8qI16/pxjzkd5Z+GMTbfqbD43mXnHPWP1Xhbjj9WBTZ0V4kY4VMd7Uvdlxjj5nHmnelQULFf8yJYjeG5RbM0GYRAriJsIOwvoky7krno34C/t/oA/iYV3bc2J9R48sElKxDr43x4is+YHiFYINktwSOn4vt6he572K0Jqj/1tulqjbcpnFJbWCfgfX5U6WJ/fFJmtSlaFp1KYBxaOJ9/sqauXjWWVIPLRZsKMdK4NRA8IcmDZt5cHW/jUT1Sc+8P1F7EIPHtcEjzoJMJPF5tcojWcE0NqwMuztAnRXVjcWdsiSIwa1hiuReruh+1u3SDfbjgetQlr5GPIw//KkU6pvZxiqywQNTMQBEQItnd4w99flkugKGm531RJtsZq3PQ5zHHFLC+1LtHXeRS7AgfmJi/X072sTuSSeUcDAdlZMCY06sWKf80PZ7alBrCD2j/NbLr5c="
before_script:
  - brew update
  - brew install sbt
  - brew install bdw-gc
  - brew link bdw-gc
  - brew install jq
  - if [ "$TRAVIS_PULL_REQUEST" != "false" ] ; then
      echo "Incoming pull request from https://github.com/$TRAVIS_REPO_SLUG/pull/$TRAVIS_PULL_REQUEST";
      author=$(curl -u dummy4dummy:dummy2dummy -s "https://api.github.com/repos/$TRAVIS_REPO_SLUG/pulls/$TRAVIS_PULL_REQUEST" | jq -r ".user.login");
      if [ $? -ne 0 ] ; then exit 1; fi;
      echo "Pull request submitted by $author";
      signed=$(curl -s http://www.lightbend.com/contribute/cla/scala/check/$author | jq -r ".signed");
      if [ $? -ne 0 ] ; then exit 1; fi;
      if [ "$signed" = "true" ] ; then
        echo "CLA check for $author successful";
      else
        echo "CLA check for $author failed";
        echo "Please sign the Scala CLA to contribute to Scala Native";
        echo "Go to https://www.lightbend.com/contribute/cla/scala and then resubmit this pull request";
        exit 1;
      fi;
    fi;
script:
  - java -version
  - sbt 'rtlib/publishLocal' 'nscplugin/publishLocal' 'publishLocal' 'sandbox/run' 'demoNative/run' 'scalafmtTest' 'publishIfOnMaster'
